apiVersion: v1
kind: Service
metadata:
  name: eks-fe-service
  namespace: praktikum-eks
spec:
  selector:
    app: eks-fe
  type: ClusterIP
  ports:
  - name: eks-fe-port
    protocol: TCP
    port: 80
    targetPort: 3000 
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.